import React from "react";


export const metadata = {
  title: "Authentication",
  description: "Generated by Next js"
}

export default function AuthLayout({
  children,
}: {
  children : React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
     
        {children}
        <footer className="p-4 bg-black text-white text-2xl">
          Footer
        </footer>
      </body>
    </html>
  );
}
