import React from "react";

export const metadata = {
  title: "About",
  description: "Generated by Next js"
}

export default function MarketingLayout({
  children,
}: {children: 
   React.ReactNode
}) {
  return (
    <html lang="en">
      <body>  
           <header className="p-4 bg-blue-400 text-2xl text-white">
        Header
      </header> 
        {children}
      </body>
    </html>
  );
}
