import "./globals.css";

export const metadata = {
  title: "Next js",
  description: "Generated by Next js"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
   
        {children}
        <footer className="p-4 bg-black text-white text-2xl">
          Footer
        </footer>
      </body>
    </html>
  );
}
