import React from "react";

export const metadata = {
  title: "Marketing",
  description: "Generated by Next js"
}

export default function MarketingLayout({
  children,
}: {children: 
   React.ReactNode
}) {
  return (
    <html lang="en">
      <body>   
        {children}
      </body>
    </html>
  );
}
